- name: Destroy k8s cluster
  gcp_container_cluster:
    name: "{{ platform_name }}-cluster"
    initial_node_count: 1
    zone: "{{ region }}-a"
    project: "{{ gcp_project_id }}"
    auth_kind: "serviceaccount"
    service_account_file: "{{ sa_path }}"
    network: "{{ platform_name }}-vpc"
    subnetwork: "{{ platform_name }}-subnet"
    scopes:
      - https://www.googleapis.com/auth/cloud-platform
    state: absent
  register: k8s_cluster

- name: Gather VPC facts
  gcp_compute_network_info:
    filters:
    - name = "{{ platform_name }}-vpc"
    auth_kind: "serviceaccount"
    service_account_file: "{{ sa_path }}"
    project: "{{ gcp_project_id }}"
  register: network_list

- name: Destroy Subnet
  gcp_compute_subnetwork:
    network: "{{ network_list['resources'][0] }}"
    name: "{{ platform_name }}-subnet"
    region: "{{ region }}"
    ip_cidr_range: "10.0.0.0/24"
    auth_kind: "serviceaccount"
    service_account_file: "{{ sa_path }}"
    project: "{{ gcp_project_id }}"
    state: absent

- name: Destroy VPC
  gcp_compute_network:
    name: "{{ platform_name }}-vpc"
    auth_kind: "serviceaccount"
    service_account_file: "{{ sa_path }}"
    project: "{{ gcp_project_id }}"
    state: absent

- name: Create list of MySQL authorized hosts
  set_fact:
    mysql_authorized_networks: "{{ mysql_authorized_networks | default([]) + [{'value': item.networkInterfaces[0].accessConfigs[0].natIP + '/32' }] }}"
  with_items: "{{ all_gke_instances['resources'] }}"
  when: item.networkInterfaces[0].network == network.selfLink
  no_log: true

- name: Destroy MySQL Cloud instance {{ mysql_authorized_networks }} {{ platform_name }} {{ sql_tag }}
  gcp_sql_instance:
    name: "{{ platform_name }}-db-{{ sql_tag }}"
    backend_type: "SECOND_GEN"
    database_version: "MYSQL_5_7"
    instance_type: "CLOUD_SQL_INSTANCE"
    settings:
      backup_configuration:
        enabled: yes
        # Default backup time which is in UTC
        start_time: "07:00"
      ip_configuration:
        authorized_networks: "{{ mysql_authorized_networks }}"
        require_ssl: yes
      tier: db-n1-standard-1
    region: "{{ region }}"
    project: "{{ gcp_project_id }}"
    auth_kind: "serviceaccount"
    service_account_file: "{{ sa_path }}"
    scopes:
      - https://www.googleapis.com/auth/cloud-platform
    state: absent
  register: db_instance

- name: Print db_instance
  ansible.builtin.debug:
    var: db_instance

- name: Destroy MySQL user
  gcp_sql_user:
    name: "pluto"
    host: "%"
    instance: "{{ db_instance }}"
    password: "{{ sql_password }}"
    project: "{{ gcp_project_id }}"
    auth_kind: "serviceaccount"
    service_account_file: "{{ sa_path }}"
    scopes:
      - https://www.googleapis.com/auth/cloud-platform
    state: absent
  no_log: true

- name: Destroy MySQL database
  gcp_sql_database:
    name: "pluto"
    charset: "utf8"
    instance: "{{ db_instance.name }}"
    project: "{{ gcp_project_id }}"
    auth_kind: "serviceaccount"
    service_account_file: "{{ sa_path }}"
    scopes:
      - https://www.googleapis.com/auth/cloud-platform
    state: absent
  register: mysql_db
